### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by Padlina** [josd/josd.github.io#1]
Dear @josd , I'm Roberta Padlina and the past 3 years I worked with Hans Cools on semantic web. I'm really sorry I'm contacting you this way, but I couldn't find another and I need to talk with you as soon as possible. Could you please send me an email at roberta.padlina@memoriav.ch so that I can explain you. Best regards

**Comment by josd** [comment]
Sorry for the late reply and in the mean time I received your email.
Thanks.
